//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavedFilters
    {
        public long Id { get; set; }
        public string FilterName { get; set; }
        public bool General { get; set; }
        public bool Default { get; set; }
        public string UserId { get; set; }
        public string GridOptions { get; set; }
        public string FilterOptions { get; set; }
        public string FilterKey { get; set; }
    }
}
